### PR TITLE
Update Dockerfile for Debian armhf

### PR DESCRIPTION
**Pull request by denis99999**
- update "LABEL Url" from openstf to devicefarmer
- install "cmake" package

Signed-off-by: Denis barbaron <denis.barbaron@orange.com>

### CODE REVIEW

**Review by koral-- — APPROVED** [review]

**Comment by denis99999** [comment]
@koral-- , an error occured during build using the standard Dockerfile, it seems it is not related to the PR, is it because a Docker Hub authentication issue ?

**Comment by denis99999** [comment]
@koral-- , I followed the procedure to set DCO but it changed nothing, I hope I did not make a mistake ?

**Comment by denis99999** [comment]
In fact, it seems I amended the merge commit with my DCO but not the initial commit, so I proposed to click on the button "Set DCO to pass" ? Sorry, next time, I will add the DCO more properly !

**Comment by koral--** [comment]
Reagrding docker authorization. I've heard about that but haven't analyzed yet how it affects our CI. We can add a bot account and put its credentials on CI if needed.
Anyway PR branch was out of date and after update it passed.

**Pull request merged**
