### PR TITLE
move off screen password autofill

### PR DESCRIPTION
**Pull request by Ristakis**
Using css moved off screen the password autofill form when trying to use keyboard

### CODE REVIEW

**Comment by koral--** [comment]
What kind of problem does it solve?

**Comment by Ristakis** [comment]
> 

image

It moves this box out of the screen

**Comment by koral--** [comment]
How to reproduce it?

**Comment by Ristakis** [comment]
> How to reproduce it?

You have to have at least 1 saved password (chrome feature) to be able to reproduce

Steps to reproduce:
Open any android device,
Focus any input,
Start typing with your keyboard (not device keypad)

This happens because the input that catches the events is of type password, and chrome wants to fill it with your saved passwords.

**Comment by koral--** [comment]
I could not reproduce that. On which browser does it happen?

**Comment by Ristakis** [comment]
@koral-- google chrome

**Comment by elenkuz** [comment]
I have the same issue with autofill form

**Comment by ZhyliaievD** [comment]
Same here  - face it from google chrome
To reproduce - send some keystrokes to the device(e.g. type in text field) OR use arrow UP/DOWN(I use it for navigation in some cases)

**Comment by koral--** [comment]
ok,got it

**Review by koral-- — APPROVED** [review]

**Pull request merged**
