### PR TITLE
fix bug on taking control of a device: set a lock for exclusive access

### PR DESCRIPTION
**Pull request by denis99999**
It fixes the #620 issue at API level

### CODE REVIEW

**Review by koral-- — APPROVED** [review]

**Comment by denis99999** [comment]
@jupe, I have tested this PR extensively and haven't seen any other issues, can you describe the issue you are experiencing? Are you sure that your client side is not at fault?

**Comment by jupe** [comment]
multiple parallel test job try to
lock same device and sometimes when time is right, two client get same device and problems starts, eg ”No longer owned by..”

**Comment by denis99999** [comment]
@jupe , can you test this PR #824 and let me know if it fixes your issue?

**Comment by jupe** [comment]
> @jupe , can you test this PR #824 and let me know if it fixes your issue?

Thanks for investigating this @denis99999 . I’ll test this as soon as possible. Note that I’m still using 3.7.1 release and a bit afraid to upgrade 3.7.2 since it introduces so many changes. Have to finally jump to it :)

**Comment by jupe** [comment]
so far seems to work fine. One (a bit related) improvement idea for tracing - when automatic leave functionality is triggered, it doesnt trace reason which would be useful; https://github.com/DeviceFarmer/stf/blob/9b8738cdbb43829468406fdebb2ed25dbbcd4d66/lib/units/device/plugins/group.js#L79

**Comment by denis99999** [comment]
> so far seems to work fine. One (a bit related) improvement idea for tracing - when automatic leave functionality is triggered, it doesnt trace reason which would be useful;

@jupe, the 'No longer owned..' message is normal and is traced when the device is released either by the one who previously took control of it, or by the admin, or by the device reservation mechanism who can preempt a device, we could indeed indicate the cause but what is the point of such an effort?

**Comment by jupe** [comment]
it would help investigations when such issue happens. Reason would identify root cause clearly.

**Comment by denis99999** [comment]
@jupe ,


> it would help investigations when such issue happens. Reason would identify root cause clearly.

You can suggest a PR but honestly it doesn't seem essential to me



> Probably not directly related, but we have strange issue when phone disconnect from USB hub causes that also other phones adb connections break on the same host. I’ve to investigate that more, but do you have any idea what could causes that?

Yes, this looks like a hardware issue, you should at least make sure you are using a USB 2.0 hub (and not 3.x as it seems STF supports it poorly) and preferably connect it to your host's USB 2.0 port, You also need to make sure your host has enough USB channels. available

**Comment by jupe** [comment]
> @jupe ,
> 
> > it would help investigations when such issue happens. Reason would identify root cause clearly.
> 
> You can suggest a PR but honestly it doesn't seem essential to me
> 
> > Probably not directly related, but we have strange issue when phone disconnect from USB hub causes that also other phones adb connections break on the same host. I’ve to investigate that more, but do you have any idea what could causes that?
> 
> Yes, this looks like a hardware issue, you should at least make sure you are using a USB 2.0 hub (and not 3.x as it seems STF supports it poorly) and preferably connect it to your host's USB 2.0 port, You also need to make sure your host has enough USB channels. available

seems that latest release fixes this issue. Reproduce every time with earlier release. Didn't find any obvious reason why it happens/how it get fixed.

**Comment by denis99999** [comment]
@jupe , interesting, perhaps it is due to the upgrade to adbkit 3.x, I will make tests with a USB 3.x Hub to check if it we gain in stability!

**Comment by jupe** [comment]
note that I did have USB 2.0 usb hub. Reproduced even with 2 phones - when pressing reboot from UI, another reserved phone connection dropped as well.

**Comment by denis99999** [comment]
so mystery

**Pull request merged**
